//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpAlert.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Allows messages with the test status when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows messages with the test status when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool statusTest {
            get {
                return ((bool)(this["statusTest"]));
            }
            set {
                this["statusTest"] = value;
            }
        }
        
        /// <summary>
        /// Allows messages with the actual status when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows messages with the actual status when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool statusActual {
            get {
                return ((bool)(this["statusActual"]));
            }
            set {
                this["statusActual"] = value;
            }
        }
        
        /// <summary>
        /// Allows message types with the alert status when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows message types with the alert status when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool messageTypeAlert {
            get {
                return ((bool)(this["messageTypeAlert"]));
            }
            set {
                this["messageTypeAlert"] = value;
            }
        }
        
        /// <summary>
        /// Allows message types with the update status when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows message types with the update status when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool messageTypeUpdate {
            get {
                return ((bool)(this["messageTypeUpdate"]));
            }
            set {
                this["messageTypeUpdate"] = value;
            }
        }
        
        /// <summary>
        /// Allows message types with the cancel status when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows message types with the cancel status when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool messageTypeCancel {
            get {
                return ((bool)(this["messageTypeCancel"]));
            }
            set {
                this["messageTypeCancel"] = value;
            }
        }
        
        /// <summary>
        /// Allows extreme messages to be relayed when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows extreme messages to be relayed when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool severityExtreme {
            get {
                return ((bool)(this["severityExtreme"]));
            }
            set {
                this["severityExtreme"] = value;
            }
        }
        
        /// <summary>
        /// Allows severe messages to be relayed when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows severe messages to be relayed when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool severitySevere {
            get {
                return ((bool)(this["severitySevere"]));
            }
            set {
                this["severitySevere"] = value;
            }
        }
        
        /// <summary>
        /// Allows moderate messages to be relayed when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows moderate messages to be relayed when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool severityModerate {
            get {
                return ((bool)(this["severityModerate"]));
            }
            set {
                this["severityModerate"] = value;
            }
        }
        
        /// <summary>
        /// Allows minor messages to be relayed when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows minor messages to be relayed when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool severityMinor {
            get {
                return ((bool)(this["severityMinor"]));
            }
            set {
                this["severityMinor"] = value;
            }
        }
        
        /// <summary>
        /// Allows all unknown severity messages to be relayed when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows all unknown severity messages to be relayed when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool severityUnknown {
            get {
                return ((bool)(this["severityUnknown"]));
            }
            set {
                this["severityUnknown"] = value;
            }
        }
        
        /// <summary>
        /// Allows urgent messages to be relayed when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows urgent messages to be relayed when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool urgencyImmediate {
            get {
                return ((bool)(this["urgencyImmediate"]));
            }
            set {
                this["urgencyImmediate"] = value;
            }
        }
        
        /// <summary>
        /// Allows expected messages to be relayed when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows expected messages to be relayed when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool urgencyExpected {
            get {
                return ((bool)(this["urgencyExpected"]));
            }
            set {
                this["urgencyExpected"] = value;
            }
        }
        
        /// <summary>
        /// Allows future messages to be relayed when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows future messages to be relayed when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool urgencyFuture {
            get {
                return ((bool)(this["urgencyFuture"]));
            }
            set {
                this["urgencyFuture"] = value;
            }
        }
        
        /// <summary>
        /// Allows past messages to be relayed when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows past messages to be relayed when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool urgencyPast {
            get {
                return ((bool)(this["urgencyPast"]));
            }
            set {
                this["urgencyPast"] = value;
            }
        }
        
        /// <summary>
        /// Only allows messages with one or more geocodes in the list. Leave this and UGC blank to allow all.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Only allows messages with one or more geocodes in the list. Leave this and UGC bl" +
            "ank to allow all.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection AllowedSAMELocations_Geocodes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AllowedSAMELocations_Geocodes"]));
            }
            set {
                this["AllowedSAMELocations_Geocodes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection EnforceEventBlacklist {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EnforceEventBlacklist"]));
            }
            set {
                this["EnforceEventBlacklist"] = value;
            }
        }
        
        /// <summary>
        /// Sets the interval between each server request in seconds.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Sets the interval between each server request in seconds.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int AlertCheckInterval {
            get {
                return ((int)(this["AlertCheckInterval"]));
            }
            set {
                this["AlertCheckInterval"] = value;
            }
        }
        
        /// <summary>
        /// Only allows messages with one or more geocodes in the list. Leave this and geocodes blank to allow all.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Only allows messages with one or more geocodes in the list. Leave this and geocod" +
            "es blank to allow all.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection AllowedCAPCPLocations_Geocodes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AllowedCAPCPLocations_Geocodes"]));
            }
            set {
                this["AllowedCAPCPLocations_Geocodes"] = value;
            }
        }
        
        /// <summary>
        /// Only allows WEA Imminent Threat CAP messages when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Only allows WEA Imminent Threat CAP messages when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool weaOnly {
            get {
                return ((bool)(this["weaOnly"]));
            }
            set {
                this["weaOnly"] = value;
            }
        }
        
        /// <summary>
        /// Existing alerts will be discarded for the first check when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Existing alerts will be discarded for the first check when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool discardFirstAlerts {
            get {
                return ((bool)(this["discardFirstAlerts"]));
            }
            set {
                this["discardFirstAlerts"] = value;
            }
        }
        
        /// <summary>
        /// When this has a value, alerts will be sent to a Discord webhook. This will disable popups.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("When this has a value, alerts will be sent to a Discord webhook. This will disabl" +
            "e popups.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DiscordWebhook {
            get {
                return ((string)(this["DiscordWebhook"]));
            }
            set {
                this["DiscordWebhook"] = value;
            }
        }
        
        /// <summary>
        /// When this has a value, it will be appended to the end of the webhook message.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("When this has a value, it will be appended to the end of the webhook message.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DiscordWebhookAppend {
            get {
                return ((string)(this["DiscordWebhookAppend"]));
            }
            set {
                this["DiscordWebhookAppend"] = value;
            }
        }
        
        /// <summary>
        /// Displays messages in fullscreen when ticked. Recommended for users with larger displays, such as TVs. (1280x720 resolution recommended)
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Displays messages in fullscreen when ticked. Recommended for users with larger di" +
            "splays, such as TVs. (1280x720 resolution recommended)")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int alertDisplayType {
            get {
                return ((int)(this["alertDisplayType"]));
            }
            set {
                this["alertDisplayType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool urgencyUnknown {
            get {
                return ((bool)(this["urgencyUnknown"]));
            }
            set {
                this["urgencyUnknown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alertFullscreenIdle {
            get {
                return ((bool)(this["alertFullscreenIdle"]));
            }
            set {
                this["alertFullscreenIdle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int alertTimeout {
            get {
                return ((int)(this["alertTimeout"]));
            }
            set {
                this["alertTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alertCompatibilityMode {
            get {
                return ((bool)(this["alertCompatibilityMode"]));
            }
            set {
                this["alertCompatibilityMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool statusWindow {
            get {
                return ((bool)(this["statusWindow"]));
            }
            set {
                this["statusWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alertTimeZoneUTC {
            get {
                return ((bool)(this["alertTimeZoneUTC"]));
            }
            set {
                this["alertTimeZoneUTC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool messageTypeTest {
            get {
                return ((bool)(this["messageTypeTest"]));
            }
            set {
                this["messageTypeTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool statusExercise {
            get {
                return ((bool)(this["statusExercise"]));
            }
            set {
                this["statusExercise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alertTTSonly {
            get {
                return ((bool)(this["alertTTSonly"]));
            }
            set {
                this["alertTTSonly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int alertVolume {
            get {
                return ((int)(this["alertVolume"]));
            }
            set {
                this["alertVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool categoryGeophysical {
            get {
                return ((bool)(this["categoryGeophysical"]));
            }
            set {
                this["categoryGeophysical"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool categorySecurity {
            get {
                return ((bool)(this["categorySecurity"]));
            }
            set {
                this["categorySecurity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool categoryMedical {
            get {
                return ((bool)(this["categoryMedical"]));
            }
            set {
                this["categoryMedical"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool categoryUtilities {
            get {
                return ((bool)(this["categoryUtilities"]));
            }
            set {
                this["categoryUtilities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool categoryMeterological {
            get {
                return ((bool)(this["categoryMeterological"]));
            }
            set {
                this["categoryMeterological"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool categoryRescue {
            get {
                return ((bool)(this["categoryRescue"]));
            }
            set {
                this["categoryRescue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool categoryEnvironmental {
            get {
                return ((bool)(this["categoryEnvironmental"]));
            }
            set {
                this["categoryEnvironmental"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool categoryToxicThreat {
            get {
                return ((bool)(this["categoryToxicThreat"]));
            }
            set {
                this["categoryToxicThreat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool categoryGeneralSafety {
            get {
                return ((bool)(this["categoryGeneralSafety"]));
            }
            set {
                this["categoryGeneralSafety"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool categoryFire {
            get {
                return ((bool)(this["categoryFire"]));
            }
            set {
                this["categoryFire"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool categoryTransportation {
            get {
                return ((bool)(this["categoryTransportation"]));
            }
            set {
                this["categoryTransportation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool categoryOtherUnknown {
            get {
                return ((bool)(this["categoryOtherUnknown"]));
            }
            set {
                this["categoryOtherUnknown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alertNoGUI {
            get {
                return ((bool)(this["alertNoGUI"]));
            }
            set {
                this["alertNoGUI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alertTitlebarControls {
            get {
                return ((bool)(this["alertTitlebarControls"]));
            }
            set {
                this["alertTitlebarControls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int storedMaxSize {
            get {
                return ((int)(this["storedMaxSize"]));
            }
            set {
                this["storedMaxSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowLocation {
            get {
                return ((int)(this["WindowLocation"]));
            }
            set {
                this["WindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisclaimerShown {
            get {
                return ((bool)(this["DisclaimerShown"]));
            }
            set {
                this["DisclaimerShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alertNoRelay {
            get {
                return ((bool)(this["alertNoRelay"]));
            }
            set {
                this["alertNoRelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StartToneLocation {
            get {
                return ((string)(this["StartToneLocation"]));
            }
            set {
                this["StartToneLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EndToneLocation {
            get {
                return ((string)(this["EndToneLocation"]));
            }
            set {
                this["EndToneLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alertIncreaseSize {
            get {
                return ((bool)(this["alertIncreaseSize"]));
            }
            set {
                this["alertIncreaseSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection EnforceSAMEEventBlacklist {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EnforceSAMEEventBlacklist"]));
            }
            set {
                this["EnforceSAMEEventBlacklist"] = value;
            }
        }
        
        /// <summary>
        /// This value defines which display to show the alert on when using the fullscreen mode.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("This value defines which display to show the alert on when using the fullscreen m" +
            "ode.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int alertFullscreenDisplay {
            get {
                return ((int)(this["alertFullscreenDisplay"]));
            }
            set {
                this["alertFullscreenDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AlertDeadInterval {
            get {
                return ((int)(this["AlertDeadInterval"]));
            }
            set {
                this["AlertDeadInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showExpiryMessages {
            get {
                return ((bool)(this["showExpiryMessages"]));
            }
            set {
                this["showExpiryMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alertPlayEndTone {
            get {
                return ((bool)(this["alertPlayEndTone"]));
            }
            set {
                this["alertPlayEndTone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegionUnitedStates {
            get {
                return ((bool)(this["RegionUnitedStates"]));
            }
            set {
                this["RegionUnitedStates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegionCanada {
            get {
                return ((bool)(this["RegionCanada"]));
            }
            set {
                this["RegionCanada"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegionMexico {
            get {
                return ((bool)(this["RegionMexico"]));
            }
            set {
                this["RegionMexico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProgramVoice {
            get {
                return ((string)(this["ProgramVoice"]));
            }
            set {
                this["ProgramVoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string MakiVersion {
            get {
                return ((string)(this["MakiVersion"]));
            }
            set {
                this["MakiVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DiscordWebhookConfirmAlerts {
            get {
                return ((bool)(this["DiscordWebhookConfirmAlerts"]));
            }
            set {
                this["DiscordWebhookConfirmAlerts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SetupExperienceComplete {
            get {
                return ((bool)(this["SetupExperienceComplete"]));
            }
            set {
                this["SetupExperienceComplete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StationIdentifier {
            get {
                return ((string)(this["StationIdentifier"]));
            }
            set {
                this["StationIdentifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StationName {
            get {
                return ((string)(this["StationName"]));
            }
            set {
                this["StationName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowNonEnglishAlerts {
            get {
                return ((bool)(this["AllowNonEnglishAlerts"]));
            }
            set {
                this["AllowNonEnglishAlerts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DiscordWebhookRelayLocally {
            get {
                return ((bool)(this["DiscordWebhookRelayLocally"]));
            }
            set {
                this["DiscordWebhookRelayLocally"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProgramAudioOutput {
            get {
                return ((string)(this["ProgramAudioOutput"]));
            }
            set {
                this["ProgramAudioOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableDialogs {
            get {
                return ((bool)(this["DisableDialogs"]));
            }
            set {
                this["DisableDialogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alertPlayStartToneTwice {
            get {
                return ((bool)(this["alertPlayStartToneTwice"]));
            }
            set {
                this["alertPlayStartToneTwice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RegionUnitedStatesNWS {
            get {
                return ((bool)(this["RegionUnitedStatesNWS"]));
            }
            set {
                this["RegionUnitedStatesNWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LegacyAudioPlayer {
            get {
                return ((bool)(this["LegacyAudioPlayer"]));
            }
            set {
                this["LegacyAudioPlayer"] = value;
            }
        }
    }
}
