//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpAlert.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Allows messages with the test status when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows messages with the test status when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool statusTest {
            get {
                return ((bool)(this["statusTest"]));
            }
            set {
                this["statusTest"] = value;
            }
        }
        
        /// <summary>
        /// Allows messages with the actual status when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows messages with the actual status when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool statusActual {
            get {
                return ((bool)(this["statusActual"]));
            }
            set {
                this["statusActual"] = value;
            }
        }
        
        /// <summary>
        /// Allows message types with the alert status when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows message types with the alert status when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool messageTypeAlert {
            get {
                return ((bool)(this["messageTypeAlert"]));
            }
            set {
                this["messageTypeAlert"] = value;
            }
        }
        
        /// <summary>
        /// Allows message types with the update status when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows message types with the update status when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool messageTypeUpdate {
            get {
                return ((bool)(this["messageTypeUpdate"]));
            }
            set {
                this["messageTypeUpdate"] = value;
            }
        }
        
        /// <summary>
        /// Allows message types with the cancel status when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows message types with the cancel status when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool messageTypeCancel {
            get {
                return ((bool)(this["messageTypeCancel"]));
            }
            set {
                this["messageTypeCancel"] = value;
            }
        }
        
        /// <summary>
        /// Allows extreme messages to be relayed when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows extreme messages to be relayed when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool severityExtreme {
            get {
                return ((bool)(this["severityExtreme"]));
            }
            set {
                this["severityExtreme"] = value;
            }
        }
        
        /// <summary>
        /// Allows severe messages to be relayed when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows severe messages to be relayed when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool severitySevere {
            get {
                return ((bool)(this["severitySevere"]));
            }
            set {
                this["severitySevere"] = value;
            }
        }
        
        /// <summary>
        /// Allows moderate messages to be relayed when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows moderate messages to be relayed when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool severityModerate {
            get {
                return ((bool)(this["severityModerate"]));
            }
            set {
                this["severityModerate"] = value;
            }
        }
        
        /// <summary>
        /// Allows minor messages to be relayed when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows minor messages to be relayed when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool severityMinor {
            get {
                return ((bool)(this["severityMinor"]));
            }
            set {
                this["severityMinor"] = value;
            }
        }
        
        /// <summary>
        /// Allows all unknown severity messages to be relayed when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows all unknown severity messages to be relayed when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool severityUnknown {
            get {
                return ((bool)(this["severityUnknown"]));
            }
            set {
                this["severityUnknown"] = value;
            }
        }
        
        /// <summary>
        /// Allows urgent messages to be relayed when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows urgent messages to be relayed when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool urgencyImmediate {
            get {
                return ((bool)(this["urgencyImmediate"]));
            }
            set {
                this["urgencyImmediate"] = value;
            }
        }
        
        /// <summary>
        /// Allows expected messages to be relayed when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows expected messages to be relayed when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool urgencyExpected {
            get {
                return ((bool)(this["urgencyExpected"]));
            }
            set {
                this["urgencyExpected"] = value;
            }
        }
        
        /// <summary>
        /// Allows future messages to be relayed when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows future messages to be relayed when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool urgencyFuture {
            get {
                return ((bool)(this["urgencyFuture"]));
            }
            set {
                this["urgencyFuture"] = value;
            }
        }
        
        /// <summary>
        /// Allows past messages to be relayed when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Allows past messages to be relayed when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool urgencyPast {
            get {
                return ((bool)(this["urgencyPast"]));
            }
            set {
                this["urgencyPast"] = value;
            }
        }
        
        /// <summary>
        /// Only allows messages with one or more geocodes in the list. Leave this and UGC blank to allow all.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Only allows messages with one or more geocodes in the list. Leave this and UGC bl" +
            "ank to allow all.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection AllowedSAMELocations_Geocodes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AllowedSAMELocations_Geocodes"]));
            }
            set {
                this["AllowedSAMELocations_Geocodes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection EnforceEventBlacklist {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EnforceEventBlacklist"]));
            }
            set {
                this["EnforceEventBlacklist"] = value;
            }
        }
        
        /// <summary>
        /// Sets the interval between each server request in seconds.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Sets the interval between each server request in seconds.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int AlertCheckInterval {
            get {
                return ((int)(this["AlertCheckInterval"]));
            }
            set {
                this["AlertCheckInterval"] = value;
            }
        }
        
        /// <summary>
        /// Only allows messages with one or more geocodes in the list. Leave this and geocodes blank to allow all.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Only allows messages with one or more geocodes in the list. Leave this and geocod" +
            "es blank to allow all.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection AllowedUGCLocations_Geocodes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AllowedUGCLocations_Geocodes"]));
            }
            set {
                this["AllowedUGCLocations_Geocodes"] = value;
            }
        }
        
        /// <summary>
        /// Only allows WEA Imminent Threat CAP messages when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Only allows WEA Imminent Threat CAP messages when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool weaOnly {
            get {
                return ((bool)(this["weaOnly"]));
            }
            set {
                this["weaOnly"] = value;
            }
        }
        
        /// <summary>
        /// Existing alerts will be discarded for the first check when ticked.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Existing alerts will be discarded for the first check when ticked.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool discardFirstAlerts {
            get {
                return ((bool)(this["discardFirstAlerts"]));
            }
            set {
                this["discardFirstAlerts"] = value;
            }
        }
        
        /// <summary>
        /// When this has a value, alerts will be sent to a Discord webhook. This will disable popups.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("When this has a value, alerts will be sent to a Discord webhook. This will disabl" +
            "e popups.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DiscordWebhook {
            get {
                return ((string)(this["DiscordWebhook"]));
            }
            set {
                this["DiscordWebhook"] = value;
            }
        }
        
        /// <summary>
        /// When this has a value, it will be appended to the end of the webhook message.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("When this has a value, it will be appended to the end of the webhook message.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DiscordWebhookAppend {
            get {
                return ((string)(this["DiscordWebhookAppend"]));
            }
            set {
                this["DiscordWebhookAppend"] = value;
            }
        }
        
        /// <summary>
        /// Displays messages in fullscreen when ticked. Recommended for users with larger displays, such as TVs. (1280x720 resolution recommended)
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Displays messages in fullscreen when ticked. Recommended for users with larger di" +
            "splays, such as TVs. (1280x720 resolution recommended)")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alertFullscreen {
            get {
                return ((bool)(this["alertFullscreen"]));
            }
            set {
                this["alertFullscreen"] = value;
            }
        }
        
        /// <summary>
        /// This value defines which display to show the alert on when using the fullscreen mode.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("This value defines which display to show the alert on when using the fullscreen m" +
            "ode.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int alertFullscreenDisplay {
            get {
                return ((int)(this["alertFullscreenDisplay"]));
            }
            set {
                this["alertFullscreenDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool urgencyUnknown {
            get {
                return ((bool)(this["urgencyUnknown"]));
            }
            set {
                this["urgencyUnknown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alertFullscreenIdle {
            get {
                return ((bool)(this["alertFullscreenIdle"]));
            }
            set {
                this["alertFullscreenIdle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int alertTimeout {
            get {
                return ((int)(this["alertTimeout"]));
            }
            set {
                this["alertTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alertCompatibilityMode {
            get {
                return ((bool)(this["alertCompatibilityMode"]));
            }
            set {
                this["alertCompatibilityMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool statusWindow {
            get {
                return ((bool)(this["statusWindow"]));
            }
            set {
                this["statusWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alertTimeZoneUTC {
            get {
                return ((bool)(this["alertTimeZoneUTC"]));
            }
            set {
                this["alertTimeZoneUTC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RunnerType {
            get {
                return ((int)(this["RunnerType"]));
            }
            set {
                this["RunnerType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("example.com")]
        public string ClientServerURL {
            get {
                return ((string)(this["ClientServerURL"]));
            }
            set {
                this["ClientServerURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9792")]
        public string ClientServerPort {
            get {
                return ((string)(this["ClientServerPort"]));
            }
            set {
                this["ClientServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool statusExercise {
            get {
                return ((bool)(this["statusExercise"]));
            }
            set {
                this["statusExercise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alertTTSonly {
            get {
                return ((bool)(this["alertTTSonly"]));
            }
            set {
                this["alertTTSonly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int alertVolume {
            get {
                return ((int)(this["alertVolume"]));
            }
            set {
                this["alertVolume"] = value;
            }
        }
    }
}
